/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal'
import { IChartData } from './interface'
export namespace Components {
  interface MetaChart {
    data: IChartData[]
  }
  interface MetaHeader {}
  interface MetaMain {}
  interface MetaMini {
    token: string
  }
  interface MetaSwap {}
}
declare global {
  interface HTMLMetaChartElement extends Components.MetaChart, HTMLStencilElement {}
  var HTMLMetaChartElement: {
    prototype: HTMLMetaChartElement
    new (): HTMLMetaChartElement
  }
  interface HTMLMetaHeaderElement extends Components.MetaHeader, HTMLStencilElement {}
  var HTMLMetaHeaderElement: {
    prototype: HTMLMetaHeaderElement
    new (): HTMLMetaHeaderElement
  }
  interface HTMLMetaMainElement extends Components.MetaMain, HTMLStencilElement {}
  var HTMLMetaMainElement: {
    prototype: HTMLMetaMainElement
    new (): HTMLMetaMainElement
  }
  interface HTMLMetaMiniElement extends Components.MetaMini, HTMLStencilElement {}
  var HTMLMetaMiniElement: {
    prototype: HTMLMetaMiniElement
    new (): HTMLMetaMiniElement
  }
  interface HTMLMetaSwapElement extends Components.MetaSwap, HTMLStencilElement {}
  var HTMLMetaSwapElement: {
    prototype: HTMLMetaSwapElement
    new (): HTMLMetaSwapElement
  }
  interface HTMLElementTagNameMap {
    'meta-chart': HTMLMetaChartElement
    'meta-header': HTMLMetaHeaderElement
    'meta-main': HTMLMetaMainElement
    'meta-mini': HTMLMetaMiniElement
    'meta-swap': HTMLMetaSwapElement
  }
}
declare namespace LocalJSX {
  interface MetaChart {
    data?: IChartData[]
  }
  interface MetaHeader {}
  interface MetaMain {}
  interface MetaMini {
    token?: string
  }
  interface MetaSwap {}
  interface IntrinsicElements {
    'meta-chart': MetaChart
    'meta-header': MetaHeader
    'meta-main': MetaMain
    'meta-mini': MetaMini
    'meta-swap': MetaSwap
  }
}
export { LocalJSX as JSX }
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'meta-chart': LocalJSX.MetaChart & JSXBase.HTMLAttributes<HTMLMetaChartElement>
      'meta-header': LocalJSX.MetaHeader & JSXBase.HTMLAttributes<HTMLMetaHeaderElement>
      'meta-main': LocalJSX.MetaMain & JSXBase.HTMLAttributes<HTMLMetaMainElement>
      'meta-mini': LocalJSX.MetaMini & JSXBase.HTMLAttributes<HTMLMetaMiniElement>
      'meta-swap': LocalJSX.MetaSwap & JSXBase.HTMLAttributes<HTMLMetaSwapElement>
    }
  }
}
